### Create a new user
POST http://localhost:3003/auth/signup
content-type: application/json

{
    "email": "test2@test2.com",
    "password": "54321"
}

# {
#     "email": "test@test.com",
#     "password": "12345"
# }

### Sign IN as an existing user
POST http://localhost:3003/auth/signin
content-type: application/json

{
    "email": "test2@test2.com",
    "password": "54321"
}

### Get the CURRENT user signed in
GET http://localhost:3003/auth/whoami

### Sign OUT the current user
POST http://localhost:3003/auth/signout

### Find user with a given ID
GET http://localhost:3003/auth/6

### Find all user with given email
GET http://localhost:3003/auth?email=sdsds@dfdf.com

### Delete user with a given ID
DELETE http://localhost:3003/auth/2333

### Update user with a given ID

PATCH http://localhost:3003/auth/3333
content-type: application/json

{
    "password": "223424"
}

# ### Set a color
# GET http://localhost:3003/auth/colors/dfdfdfdfdfd

# ### Get a color
# GET http://localhost:3003/auth/colors